# Generated by Django 4.2.5 on 2023-09-17 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0004_alter_book_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn_10", models.CharField(blank=True, max_length=10)),
                ("isbn_13", models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="number",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="demo.booknumber",
            ),
        ),
    ]
