# Generated by Django 4.2.5 on 2023-09-17 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0006_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="demo.book",
            ),
        ),
    ]
