# Generated by Django 4.2.5 on 2023-09-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0007_alter_character_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("books", models.ManyToManyField(to="demo.book")),
            ],
        ),
    ]
